// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entity "go-resepee-api/entity"

	mock "github.com/stretchr/testify/mock"
)

// AbstractApiRepositoryInterface is an autogenerated mock type for the AbstractApiRepositoryInterface type
type AbstractApiRepositoryInterface struct {
	mock.Mock
}

// ValidateEmail provides a mock function with given fields: email
func (_m *AbstractApiRepositoryInterface) ValidateEmail(email string) (entity.AbstractEmailValidation, error) {
	ret := _m.Called(email)

	var r0 entity.AbstractEmailValidation
	if rf, ok := ret.Get(0).(func(string) entity.AbstractEmailValidation); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(entity.AbstractEmailValidation)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
