// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entity "go-resepee-api/entity"

	mock "github.com/stretchr/testify/mock"
)

// FileRepositoryInterface is an autogenerated mock type for the FileRepositoryInterface type
type FileRepositoryInterface struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *FileRepositoryInterface) FindByID(id int) (entity.File, error) {
	ret := _m.Called(id)

	var r0 entity.File
	if rf, ok := ret.Get(0).(func(int) entity.File); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.File)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: file
func (_m *FileRepositoryInterface) Store(file *entity.File) (entity.File, error) {
	ret := _m.Called(file)

	var r0 entity.File
	if rf, ok := ret.Get(0).(func(*entity.File) entity.File); ok {
		r0 = rf(file)
	} else {
		r0 = ret.Get(0).(entity.File)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.File) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
