// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entity "go-resepee-api/entity"

	mock "github.com/stretchr/testify/mock"
)

// MaterialRepositoryInterface is an autogenerated mock type for the MaterialRepositoryInterface type
type MaterialRepositoryInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MaterialRepositoryInterface) Get() ([]entity.Material, error) {
	ret := _m.Called()

	var r0 []entity.Material
	if rf, ok := ret.Get(0).(func() []entity.Material); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Material)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: material
func (_m *MaterialRepositoryInterface) Store(material *entity.Material) (entity.Material, error) {
	ret := _m.Called(material)

	var r0 entity.Material
	if rf, ok := ret.Get(0).(func(*entity.Material) entity.Material); ok {
		r0 = rf(material)
	} else {
		r0 = ret.Get(0).(entity.Material)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Material) error); ok {
		r1 = rf(material)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
