server:
  address: localhost:3000
database:
  host: localhost
  port: 3306
  username: root
  password: ""
  db: resepee_db
jwt:
  secret: iBmJGmljD71NKbKbSceK
  expired: 1
abstract_api:
  key: fa5bbad97cc54246a269253751efe3e6